name: Create resources

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - master
      - draft
      - candidate
  pull_request:
    branches: 
      - main
      - master
      - draft
      - candidate
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "release.json"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        # Only runs if all of the files exists
        run: | 
          echo Release token does not exist, exiting..
          exit 1
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed

          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas csv-diff requests pybase64 configparser xmltodict

#      - name: Get branch name
#        run: echo ${GITHUB_REF##*/}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs
          
      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Run the publisher - don't run the batch script but run the line directly
          args: java -jar ./input-cache/publisher.jar publisher -ig .

      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
      - name: npm install
        run: npm install sushi fsh-sushi


      - name: execute py script # run 
        run: python release.py

      - name: Deploy candidate
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ steps.branch-name.outputs.is_default }} == 'false'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./output # The folder the action should deploy.
          target-folder: releases/${{ steps.branch-name.outputs.current_branch }}
          commit-message: Deploy candidate release to gh-pages
          clean: false 


#      - name: commit files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git diff --quiet && git diff --staged --quiet || git commit -m "create resources.csv" -a
          
#      - name: push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: main  
